### ISSUE TITLE
Getting error `no property `None` for type `int` on compiling on linux

### ISSUE THREAD

**Issue by sanket143** [Inochi2D/inochi-creator#14]
Getting this error on main branch

```
source/creator/widgets/inputtext.d(24,86): Error: no property `None` for type `int`
source/creator/widgets/controller.d(11,6): Error: undefined identifier `Parameter`
source/creator/widgets/drag.d(22,132): Error: no property `None` for type `int`
source/creator/frames/parameters.d(17,6): Error: undefined identifier `Parameter`
/usr/bin/dmd failed with exit code 1.
```
What I did
```shell
[sanket143@lisa inochi-creator:main ]$ dub
Unresolvable dependencies to package bindbc-imgui:
  inochi-creator 0.5.0-beta.3+commit.16.gb2f9131 depends on bindbc-imgui ~>1.0.0
[sanket143@lisa inochi-creator:main ]$ dub add bindbc-imgui
Adding dependency bindbc-imgui ~>0.6.0
[sanket143@lisa inochi-creator:main ]$ dub
Unresolvable dependencies to package inochi2d:
  inochi-creator 0.5.0-beta.3+commit.16.gb2f9131 depends on inochi2d ~>1.0.0
[sanket143@lisa inochi-creator:main ]$ dub add inochi2d
Adding dependency inochi2d >=0.4.0-beta <0.5.0-0
[sanket143@lisa inochi-creator:main ]$ dub
Fetching mir-core 1.1.76 (getting selected version)...
Fetching mir-algorithm 3.10.79 (getting selected version)...
Performing "debug" build using /usr/bin/dmd for x86_64.
bindbc-loader 0.3.2: building configuration "noBC"...
bindbc-opengl 0.13.0: building configuration "dynamic"...
bindbc-sdl 0.21.4: building configuration "dynamic"...
bindbc-imgui 0.6.0: building configuration "dynamic"...
gl3n 1.3.1: building configuration "library"...

```

**Comment by LunaTheFoxgirl** [comment]
Inochi2D and Inochi Creator are still in a phase of rapid development, doing dub add replaces the dependencies on the main branch with older versions on the dub database. clone the inochi2d repository and the bindbc-imgui repositories and use `dub add-local` to add them as local packages at version 1.0.0

You'll need to compile cimgui from source (which you can find in the bindbc-imgui source tree, you just need to recursively update its sub modules)

**Comment by playmer** [comment]
Expanding a tiny bit more, if you have issues building that cimgui in the bindbc repo on Linux, please raise the issue in the bindbc repo, as it's our fault, not cimguis. I need to write better docs about this whole process and I don't have a primary Linux machine atm.

**Comment by sanket143** [comment]
thanks, I got it to compile successfully but it failed with a segmentation fault. It seems it's the same issue as discussed in https://github.com/Inochi2D/inochi-creator/issues/1

```
GLInfo:
        4.6 (Compatibility Profile) Mesa 21.2.0
        Intel
        Mesa Intel(R) HD Graphics 520 (SKL GT2)
        4.60
        gls=gl33
```

**Comment by LunaTheFoxgirl** [comment]
Have you compiled cimgui from source and make installed it?

**Comment by sanket143** [comment]
Yes, I did

**Comment by sanket143** [comment]
Since I got segmentation fault, I ran it through gdb and got this
```gdb
(gdb) bt -full
#0  0x00007ffff7d90e61 in __strncmp_avx2 () at /usr/lib/libc.so.6
#1  0x00007ffff79327e8 in ImGui_ImplSDL2_Init(SDL_Window*, void*) () at ./cimgui.so
#2  0x00007ffff7932887 in ImGui_ImplSDL2_InitForOpenGL () at ./cimgui.so
#3  0x000055555573bf20 in _D7creator4core16incCreateContextFZv () at source/creator/core/package.d:209
#4  0x000055555573bc3f in _D7creator4core13incOpenWindowFZv () at source/creator/core/package.d:179
        sdlSupport = <incomplete type>
        imSupport = <incomplete type>
        flags = <incomplete type>
        support = <incomplete type>
#5  0x00005555556f84fc in _Dmain (args=...) at source/app.d:28
```

```gdb
Thread 1 "inochi-creator" received signal SIGSEGV, Segmentation fault.
0x00007ffff7d90e61 in __strncmp_avx2 () from /usr/lib/libc.so.6
```

I am not much familiar with `dlang` and `.so` files, can I say that the issue was in building the `cimgui.so`?

**Comment by LunaTheFoxgirl** [comment]
Potentially, it's at least not finding the imgui .so file.
