### ISSUE TITLE
[BUG] crash when attempting to split parameters

### ISSUE THREAD

**Issue by amelielavender** [Inochi2D/inochi-creator#284]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

this is using the latest release via flatpak, i am trying to split parameters, dragging any Part over to split it crashes the app.

opening the app thru terminal spits out `inochi-creator: /srv/buildbot/worker/build-x86_64-3/build/.flatpak-builder/build/Inochi-Creator-1/.flatpak-dub/bindbc-imgui-0.7.0+build.22.gb3d6e32/deps/cimgui/imgui/imgui.cpp:8804: void ImGuiStackSizes::CompareWithCurrentState(): Assertion SizeOfGroupStack == g.GroupStack.Size && "BeginGroup/EndGroup Mismatch!"' failed.` upon crashing.

i have tried splitting parameters several times with my own model and Aka.inx. i receive the same results every time.

### Reproduction

1. have armed parameters
2. click on cog menu > split
3. drag any part allowed into the second box
4. closes suddenly

### System Architecture

x86_64

### Operating System

Linux

### Version

0.8.0

**Comment by grillo-delmal** [comment]
I was able to reproduce it both on the stable flatpak and on the latest nightly build. 

Here is a backtrace on the latest nightly build:

```c++
inochi-creator: /__w/inochi-creator-nightly/inochi-creator-nightly/.flatpak-builder/build/Inochi-Creator-1/.flatpak-dub/i2d-imgui-0.8.0+build.2.gb171b85/deps/cimgui/imgui/imgui.cpp:8804: void ImGuiStackSizes::CompareWithCurrentState(): Assertion `SizeOfGroupStack == g.GroupStack.Size && "BeginGroup/EndGroup Mismatch!"' failed.

Thread 1 "inochi-creator" received signal SIGABRT, Aborted.
0x00007ffff7691184 in __pthread_kill_implementation () from /usr/lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff7691184 in __pthread_kill_implementation () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff763f00e in raise () from /usr/lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff76287fc in abort () from /usr/lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff762871b in __assert_fail_base.cold () from /usr/lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff7637657 in __assert_fail () from /usr/lib/x86_64-linux-gnu/libc.so.6
#5  0x00005555556ca5bf in ImGuiStackSizes::CompareWithCurrentState (this=this@entry=0x555556e353cc)
    at /__w/inochi-creator-nightly/inochi-creator-nightly/.flatpak-builder/build/Inochi-Creator-1/.flatpak-dub/i2d-imgui-0.8.0+build.2.gb171b85/deps/cimgui/imgui/imgui.cpp:8804
#6  0x00005555556d5e97 in ImGui::End ()
    at /__w/inochi-creator-nightly/inochi-creator-nightly/.flatpak-builder/build/Inochi-Creator-1/.flatpak-dub/i2d-imgui-0.8.0+build.2.gb171b85/deps/cimgui/imgui/imgui.cpp:7185
#7  0x00005555555d01e2 in _D7creator7windows6Window6updateMFZv (this=0x7fffbbd67180) at source/creator/windows/package.d:113
#8  _D7creator7windows16incUpdateWindowsFZv () at source/creator/windows/package.d:248
#9  0x00005555556a9ac8 in _D3app9incUpdateFZv () at source/app.d:136
#10 0x00005555556a997a in _Dmain (args=...) at source/app.d:97
```

**Comment by LunaTheFoxgirl** [comment]
This commit should fix it https://github.com/Inochi2D/inochi-creator/commit/c57815ed2626e73731c7ec32460f46cc39cfe716
